---
- name: install firewalld
  package:
    name: firewalld
    state: present
  register: firewalld_install
  when: managed_firewalld.enabled|default(false)|bool == true

- name: start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: firewalld_install is success and managed_firewalld.enabled|default(false)|bool == true

- name: allow access from RFC1918 networks
  firewalld:
    state: enabled
    permanent: yes
    source: '{{ item }}'
  with_items:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  when: firewalld_install is success and managed_firewalld.enabled|default(false)|bool == true
  notify: restart firewalld

- name: allow SSH
  firewalld:
    state: enabled
    permanent: yes
    service: ssh
  when: firewalld_install is success and managed_firewalld.enabled|default(false)|bool == true
  notify: restart firewalld
