---
- name: install openssh, openssh-server, openssh-clients
  tags: openssh
  become: true
  package:
    name: ['openssh', 'openssh-server', 'openssh-clients']
    state: present
  register: openssh_install
  when: managed_sshd.enabled|default(false)|bool == true

- name: configure /etc/ssh/ssh_config
  tags: openssh
  become: true
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644
  when:
  - openssh_install is success
  - managed_sshd.enabled|default(false)|bool == true

- name: configure /etc/sshd/sshd_config & /etc/sysconfig/sshd
  tags: openssh
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
  - { src: sshd_config.j2, dest: /etc/ssh/sshd_config, mode: '0600' }
  - { src: sshd_sysconfig.j2, dest: /etc/sysconfig/sshd, mode: '0640' }
  when:
  - openssh_install is success
  - managed_sshd.enabled|default(false)|bool == true
  notify:
  - restart sshd

- name: start and enable sshd service
  tags: openssh
  become: true
  service:
    name: sshd
    state: started
    enabled: yes
  when:
  - openssh_install is success
  - managed_sshd.enabled|default(false)|bool == true
