---
- name: configure /etc/resolv.conf
  tags: resolvconf
  become: true
  template:
    src: resolv_conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: managed_resolvconf.enabled|default(false)|bool == true
