---
- name: restart gdrive-crypt
  service:
    name: gdrive-crypt
    state: restarted

- name: restart gdrive-crypt-http
  service:
    name: gdrive-crypt-http
    state: restarted

- name: reload systemd
  command: /usr/bin/systemctl daemon-reload

- name: reload ufw
  command: /usr/sbin/ufw reload
