---
- hosts: all
  roles:
  - managed_ansibleuser
  - role: managed_lvm
    managed_lvm:
      enabled: false
  - managed_sshd
  - managed_ufw
  - managed_fail2ban
  - managed_ntp
  - managed_ssmtp
  - managed_nplan
  - managed_vmtools
  - managed_sysctl
  - managed_services
  - managed_packages
  - managed_timezone
  - managed_hostname
  - managed_hosts
  - managed_motd
  - managed_prompt
  - managed_proxy
  tasks:
  # Add custom User (yourself)
  - name: adduser changeme
    user:
      name: changeme
      comment: Change Me
      groups: sudo
      shell: /bin/bash
      create_home: true
      ssh_key_file: "{{ lookup('file', '~/.ssh/id_rsa') }}"
  - name: add authorized_key for onkeldom
    authorized_key:
      user: changeme
      state: present
      exclusive: true
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
