---
- hosts: all
  roles:
  - managed_ansibleuser
  - managed_admin
  - managed_sshd
  - managed_sysctl
  - managed_services
  - managed_timezone
  - managed_hostname
  - managed_hosts
  - managed_motd
  - managed_prompt
