---
- hosts: srv03.onkeldom.eu
  roles:
    - role: managed_hostname
      managed_hostname:
        enabled: true
        fqdn: srv03.onkeldom.eu
- hosts:
  - node01.onkeldom.local
  roles:
    - role: managed_hostname
      managed_hostname:
        enabled: true
        fqdn: "node01.onkeldom.local"
- hosts:
  - mgmt01.onkeldom.local
  roles:
    - role: managed_hostname
      managed_hostname:
        enabled: true
        fqdn: "mgmt01.onkeldom.local"
- hosts:
  - mgmt02.onkeldom.local
  roles:
    - role: managed_hostname
      managed_hostname:
        enabled: true
        fqdn: "mgmt02.onkeldom.local"

- hosts: all
  roles:
  - managed_deployuser
  - managed_sshd
  - managed_packages
  - managed_vmtools
  - managed_motd
  - managed_timezone
  - managed_resolvconf
  - managed_hosts
#  - managed_hostname
  - managed_services
  - managed_prompt
  - managed_chrony
  tasks:
  - name: adduser onkeldom
    user:
      name: onkeldom
      comment: Dominik Lenhardt
      groups: wheel
      shell: /bin/bash
      create_home: true
      ssh_key_file: "{{ lookup('file', '/home/onkeldom/.ssh/id_rsa') }}"
  - name: add authorized_key for onkeldom
    authorized_key:
      user: onkeldom
      state: present
      exclusive: true
      key: "{{ lookup('file', '/home/onkeldom/.ssh/id_rsa.pub') }}"
