---
- hosts: all
  roles:
  - ansible-base-deployuser
  - ansible-base-packages
  - ansible-base-vmtools
  - ansible-base-sshd
  - ansible-base-motd
  - ansible-base-timezone
  - ansible-os-chrony
  - ansible-os-update
  tasks:
  - name: adduser onkeldom
    user:
      name: onkeldom
      comment: Dominik Lenhardt
      groups: wheel
      shell: /bin/bash
      create_home: true
      ssh_key_file: "{{ lookup('file', '/home/onkeldom/.ssh/id_rsa') }}"
  - name: add authorized_key for onkeldom
    authorized_key:
      user: onkeldom
      state: present
      exclusive: true
      key: "{{ lookup('file', '/home/onkeldom/.ssh/id_rsa.pub') }}"
  - name: copy bash promt
    copy:
      src: files/bash_prompt.sh
      dest: /etc/profile.d/prompt.sh
      mode: 0644
      owner: root
