---
- name: install caddy
  tags: caddy
  become: true
  package:
    name: caddy
    state: present
  register: caddy_install
  when: infra_caddy.enabled|default(false)|bool == true

- name: create caddy logfolder
  tags: caddy
  become: true
  file:
    path: /var/log/caddy
    state: directory
    owner: root
    group: caddy
    mode: 0775

- name: configure /etc/caddy/caddy.conf
  tags: caddy
  become: true
  template:
    src: caddy_conf.j2
    dest: /etc/caddy/caddy.conf
    owner: root
    group: root
    mode: 0644
  when:
  - caddy_install is success
  - infra_caddy.enabled|default(false)|bool == true
  notify:
  - restart caddy

- name: configure /etc/caddy/conf.d/sites.conf
  tags: caddy
  become: true
  template:
    src: caddy_vhost.j2
    dest: /etc/caddy/conf.d/sites.conf
    owner: root
    group: root
    mode: 0644
  when:
  - caddy_install is success
  - infra_caddy.enabled|default(false)|bool == true
  notify:
  - restart caddy

- name: start and enable caddy service
  tags: caddy
  become: true
  service:
    name: caddy
    state: started
    enabled: yes
  when:
  - caddy_install is success
  - infra_caddy.enabled|default(false)|bool == true
