---
- name: install packages
  tags: install_packages
  become: true
  package: name={{ item }} state=present
  with_items:
    - "{{ managed_packages.install }}"
  when: managed_packages.enabled|default(false)|bool == true

- name: remove packages
  tags: remove_packages
  become: true
  package: name={{ item }} state=absent
  with_items:
    - "{{ managed_packages.remove }}"
  when: managed_packages.enabled|default(false)|bool == true
