---
- name: disable services
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
    masked: true
  ignore_errors: true
  with_items:
    - "{{ managed_services_disabled }}"
  when:
    - managed_services.enabled|default(false)|bool == true

- name: enable services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  ignore_errors: true
  with_items:
    - "{{ managed_services_active }}"
  when:
    - managed_services_enabled|default(false)|bool == true
