---
- name: install open-vm-tools
  package:
    name: open-vm-tools
    state: present
  register: openvmtools_install
  when: managed_vmtools.enabled|default(false)|bool == true and ansible_virtualization_type == "VMware"

- name: start and enable open-vm-tools
  service:
    name: open-vm-tools
    state: started
    enabled: yes
  when: openvmtools_install is success and ansible_virtualization_type == "VMware"
