---
- name: configure /etc/profile.d/prompt.sh
  template:
    src: prompt.j2
    dest: /etc/profile.d/prompt.sh
    owner: root
    group: root
    mode: 0644
  when:
    - managed_prompt_enabled|default(false)|bool == true
