---
- name: create config folders
  file:
    path: "{{ item.folder }}"
    state: directory
    owner: "{{ media_tautulli_service_user }}"
    group: "{{ media_tautulli_service_group }}"
    mode: "{{ item.mode }}"
  with_items:
  - folder: "/home/{{ media_tautulli_service_user }}/.config"
    mode: "0750"
  - folder: "/home/{{ media_tautulli_service_user }}/.config/tautulli"
    mode: "0750"
  - folder: "{{ media_tautulli_installdir }}"
    mode: "0755"
  when:
    - media_tautulli_enabled|default(false)|bool == true

- name: clone https://github.com/Tautulli/Tautulli.git
  git:
    repo: 'https://github.com/Tautulli/Tautulli.git'
    dest: "{{ media_tautulli_installdir }}"
    update: no
  become: true
  become_user: "{{ media_tautulli_service_user }}"
  register: tautulli_clone
  when:
    - media_tautulli_enabled|default(false)|bool == true

- name: configure tautulli
  template:
    src: tautulli_conf.j2
    dest: "/home/{{ media_tautulli_service_user }}/.config/tautulli/config.ini"
    owner: "{{ media_tautulli_service_user }}"
    group: "{{ media_tautulli_service_group }}"
    mode: 0640
    force: no
  when:
    - media_tautulli_enabled|default(false)|bool == true
    - tautulli_clone is success
  notify:
    - restart tautulli

- name: copy tautulli systemd unit
  template:
    src: tautulli_service.j2
    dest: "/etc/systemd/system/tautulli.service"
    owner: root
    group: root
    mode: 0644
    force: yes
  when:
    - media_tautulli_enabled|default(false)|bool == true
    - tautulli_clone is success
  notify:
    - reload systemd
    - restart tautulli

- block:
  - name: copy tautulli ufw role
    template:
      src: ufw-tautulli.j2
      dest: /etc/ufw/applications.d/ufw-tautulli
      owner: root
      group: root
      mode: 0644
    when:
      - media_tautulli_enabled|default(false)|bool == true
      - tautulli_clone is success

  - name: UFW allow Tautulli
    ufw:
      rule: allow
      name: Tautulli
    notify: reload ufw
  when:
    - media_tautulli_enabled|default(false)|bool == true
    - tautulli_clone is success
    - media_tautulli_use_firewall|default(false)|bool == true

- name: start and enable tautulli services
  service:
    name: tautulli
    state: restarted
    enabled: yes
  when:
    - media_tautulli_enabled|default(false)|bool == true
    - tautulli_clone is success
