---
- name: add sysctl entrys
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: no
    ignoreerrors: yes
  with_items: "{{ managed_sysctl_add }}"
  register: managed_sysctl_added
  when:
    - managed_sysctl_enabled|default(false)|bool == true
    - managed_sysctl_add is defined

- name: remove sysctl entrys
  sysctl:
    name: "{{ item.name }}"
    state: absent
    reload: no
    ignoreerrors: yes
  with_items: "{{ managed_sysctl_remove }}"
  register: managed_sysctl_removed
  when:
    - managed_sysctl.enabled|default(false)|bool == true
    - managed_sysctl_remove is defined

- name: reload sysctl
  command: /bin/true
  notify:
    - reload sysctl.conf
  when:
    - managed_sysctl.enabled|default(false)|bool == true
    - managed_sysctl_removed.changed
    - managed_sysctl_added.changed
