---
- name: install caddy
  package:
    name: caddy
    state: present
  register: caddy_install
  when: app_caddy.enabled|default(false)|bool == true

- name: configure /etc/caddy/caddy.conf
  template:
    src: caddy_conf.j2
    dest: /etc/caddy/caddy.conf
    owner: root
    group: root
    mode: 0644
  when:
  - caddy_install is success
  - app_caddy.enabled|default(false)|bool == true
  notify: restart caddy

- name: configure /etc/caddy/conf.d/sites.conf
  template:
    src: caddy_vhost.j2
    dest: /etc/caddy/conf.d/sites.conf
    owner: root
    group: root
    mode: 0644
  when:
  - caddy_install is success
  - app_caddy.enabled|default(false)|bool == true
  notify: restart caddy

- name: configure system settings, file descriptors and number of threads
  pam_limits:
    domain: caddy
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
  - { limit_type: '-', limit_item: 'nofile', value: 8192 }
  - { limit_type: '-', limit_item: 'nproc', value: 8192 }
  - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
  - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }
- name: reload settings from all system configuration files
  shell: sysctl --system

- name: allow webserver on ufw
  ufw:
    rule: allow
    name: "WWW Full"
  when:
  - caddy_install is success
  - app_caddy.enabled|default(false)|bool == true
  notify: restart ufw

- name: start and enable caddy service
  tags: caddy
  become: true
  service:
    name: caddy
    state: started
    enabled: yes
  when:
  - caddy_install is success
  - app_caddy.enabled|default(false)|bool == true
