---
- name: configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: "{{ managed_hosts_backup | default(true) }}"
    owner: root
    group: root
    mode: 0644
  when:
    - managed_hosts_enabled|default(false)|bool == true
