- name: configure /etc/profile.d/proxy.sh & /etc/apt/apt.conf.d/proxy.sh & /etc/wgetrc & /etc/.curlrc
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
  - { src: proxy.sh.j2, dest: /etc/profile.d/proxy.sh }
  - { src: apt.j2, dest: /et/apt/apt.conf.d/00proxy }
  - { src: wget.j2, dest: /etc/wgetrc }
  - { src: curl.j2, dest: /etc/.curlrc }
  when: managed_proxy.enabled|default(false)|bool == true

- name: configure git proxy (http)
  shell: "git config --global http.proxy {{ managed_proxy.config.protocol }}://{% if managed_proxy.config.user is defined %}{{ managed_proxy.config.user }}{% if managed_proxy.config.pass is defined %}:{{ managed_proxy.config.pass }}{% endif %}@{% endif %}{{ managed_proxy.config.url }}:{{ managed_proxy.config.port }}"
  ignore_errors: yes
  when: managed_proxy.enabled|default(false)|bool == true

- name: configure git proxy (https)
  shell: "git config --global https.proxy {{ managed_proxy.config.protocol }}://{% if managed_proxy.config.user is defined %}{{ managed_proxy.config.user }}{% if managed_proxy.config.pass is defined %}:{{ managed_proxy.config.pass }}{% endif %}@{% endif %}{{ managed_proxy.config.url }}:{{ managed_proxy.config.port }}"
  ignore_errors: yes
  when: managed_proxy.enabled|default(false)|bool == true
