---
- name: install ufw
  package:
    name: ufw
    state: present
  register: ufw_install
  when:
    - managed_ufw_enabled|default(false)|bool == true

- name: start and enable ufw
  service:
    name: ufw
    state: started
    enabled: yes
  when:
    - managed_ufw_enabled|default(false)|bool == true
    - ufw_install is success

- name: enable logging
  ufw:
    state: enabled
    logging: on
  when:
    - managed_ufw_enabled|default(false)|bool == true
    - ufw_install is success
  notify: reload ufw

- name: reject auth
  ufw:
    rule: reject
    port: auth
    log: yes
  when:
    - managed_ufw_enabled|default(false)|bool == true
    - ufw_install is success
  notify: reload ufw

- name: set limit sshd connections
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  when:
    - managed_ufw_enabled|default(false)|bool == true
    - ufw_install is success
  notify: reload ufw

- name: allow access from RFC1918 networks
  ufw:
    rule: allow
    src: '{{ item }}'
  with_items:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  when:
    - managed_ufw_enabled|default(false)|bool == true
    - ufw_install is success
  notify: reload ufw

- name: allow SSH
  ufw:
    rule: allow
    name: SSH
  when:
    - managed_ufw_enabled|default(false)|bool == true
    - ufw_install is success
  notify: reload ufw
