---
- name: install fail2ban
  package:
    name: fail2ban
    state: present
  register: fail2ban_install
  when: managed_fail2ban.enabled|default(false)|bool == true

- name: configure /etc/fail2ban/fail2ban.conf & /etc/fail2ban/jail.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - {src: fail2ban_conf.j2 ,dest: /etc/fail2ban/fail2ban.conf}
  - {src: jail_conf.j2 ,dest: /etc/fail2ban/jail.conf}
  when: fail2ban_install is success and managed_fail2ban.enabled|default(false)|bool == true
  notify: restart fail2ban

- name: start and enable fail2ban service
  become: true
  service:
    name: fail2ban
    state: started
    enabled: yes
  when: fail2ban_install is success and managed_fail2ban.enabled|default(false)|bool == true
