---
- name: configure /etc/resolv.conf
  template:
    src: resolv_conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when:
    - managed_resolvconf_enabled|default(false)|bool == true
  notify:
    - restart NetworkManager
