---
- name: install fail2ban
  package:
    name: fail2ban
    state: present
  register: fail2ban_install
  when:
    - managed_fail2ban_enabled|default(false)|bool == true

- name: configure /etc/fail2ban/fail2ban.conf
  template:
    src: fail2ban_conf.j2
    dest: /etc/fail2ban/fail2ban.conf
    owner: root
    group: root
    mode: 0644
  when:
    - managed_fail2ban_enabled|default(false)|bool == true
    - fail2ban_install is success
  notify: restart fail2ban

- name: configure /etc/fail2ban/jail.conf
  template:
    src: jail_conf.j2
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
    mode: 0644
  when:
    - managed_fail2ban_enabled|default(false)|bool == true
    - fail2ban_install is success
  notify: restart fail2ban

- name: start and enable fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes
  when:
    - managed_fail2ban_enabled|default(false)|bool == true
    - fail2ban_install is success
