---
- name: install packages
  package:
    name: ['java-1.8.0-openjdk', 'mediainfo', 'libmediainfo', 'libzen']
    state: present
  register: filebot_install
  when:
    - media_filebot_enabled|default(false)|bool == true

- name: "check if filebot is installed"
  stat:
    path: "{{ media_filebot_installdir }}/filebot.sh"
  register: filebot_bin
  when:
    - media_filebot_enabled|default(false)|bool == true

- name: copy filebot tar
  copy:
    src: "{{ role_path }}/files/{{ media_filebot_filename }}"
    dest: "/tmp/{{ media_filebot_filename }}"
    owner: root
    group: root
  when:
    - media_filebot_enabled|default(false)|bool == true and not filebot_bin.stat.exists
    - filebot_install is success

- name: "ensure install directory exists"
  file:
    path: "{{ media_filebot_installdir }}"
    state: directory
    owner: {{ media_filebot_user }}
    group: root
  when:
    - media_filebot_enabled|default(false)|bool == true
    - filebot_install is success

- name: "ensure the binaries are arextracted"
  unarchive:
    copy: "no"
    src: "/tmp/{{ media_filebot_filename }}"
    dest: "{{ media_filebot_installdir }}/"
  when:
    - media_filebot_enabled|default(false)|bool == true and not filebot_bin.stat.exists
    - filebot_install is success

- name: "ensure link on path to filebot bin"
  file:
    src: "{{ media_filebot_install }}/filebot.sh"
    dest: "{{ media_filebot_bin }}"
    state: link
  when:
    - media_filebot_enabled|default(false)|bool == true
    - filebot_install is success

- name: "remove installer from tmp"
  file:
    path: "/tmp/{{ media_filebot_filename }}"
    state: absent
  when:
    - media_filebot_enabled|default(false)|bool == true
    - filebot_install is success

- name: change ownership of filebot folder
  command: "chown -R {{ media_filebot_service_user }} {{ media_filebot_installdir }}"
  when:
    - media_filebot_enabled|default(false)|bool == true
    - filebot_install is success

- name: copy config for opensubtitles
  template:
    src: prefs.properties.j2
    dest: "{{ media_filebot_installdir }}/data/prefs.properties"
    owner: "{{ media_filebot_service_user }}"
    group: root
    mode: 0644
  when:
    - media_filebot_enabled|default(false)|bool == true
    - filebot_install is success

- name: set symlinks for libs
  file:
    src: "{{ item.src }}"
    dest: "{{ media_filebot_installdir }}/{{ item.dest }}"
    state: link
  with_items:
  - src: /usr/lib64/libmediainfo.so.0
    dest: libmediainfo.so
  - src: /usr/lib64/libzen.so.0
    dest: libzen.so
  when:
    - media_filebot_enabled|default(false)|bool == true
    - filebot_install is success
