---
- name: install rpmfusion repos
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-29.noarch.rpm
  when:
    - media_rclone_enabled|default(false)|bool == true

- name: install packages
  package:
    name: ['fuse', 'https://downloads.rclone.org/rclone-current-linux-amd64.rpm']
    state: present
  register: package_install
  when:
    - media_rclone_enabled|default(false)|bool == true

- name: create folders
  file:
    path: "{{ item.folder }}"
    state: directory
    owner: "{{ media_rclone_service_user }}"
    group: "{{ media_rclone_service_group }}"
    mode: "{{ item.mode }}"
  with_items:
  - folder: "/home/{{ media_rclone_service_user }}/.config"
    mode: "0750"
  - folder: "/home/{{ media_rclone_service_user }}/.config/rclone"
    mode: "0750"
  - folder: "/mnt/google"
    mode: "0755"
  - folder: "{{ media_rclone_mountfolder }}"
    mode: "0755"
  when:
    - media_rclone_enabled|default(false)|bool == true
    - package_install is success

- name: configure /etc/fuse.conf
  replace:
    path: /etc/fuse.conf
    regexp: '{{ item.key }}'
    replace: '{{ item.value }}'
  with_items:
    - key: '# mount_max = 1000'
      value: 'mount_max = 1000'
    - key: '# user_allow_other'
      value: 'user_allow_other'
  when:
    - media_rclone_enabled|default(false)|bool == true
    - package_install is success

- name: configure rclone
  template:
    src: rclone_conf.j2
    dest: "/home/{{ media_rclone_service_user }}/.config/rclone/rclone.conf"
    owner: "{{ media_rclone_service_user }}"
    group: "{{ media_rclone_service_group }}"
    mode: 0640
    force: no
  when:
    - media_rclone_enabled|default(false)|bool == true
    - package_install is success
  notify:
    - restart gdrive-crypt
    - restart gdrive-crypt-http

- name: copy systemd units
  template:
    src: "{{ item.src }}"
    dest: "/etc/systemd/system/{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - src: gdrive-crypt.j2
      dest: gdrive-crypt.service
    - src: gdrive-crypt-http.j2
      dest: gdrive-crypt-http.service
  when:
    - media_rclone_enabled|default(false)|bool == true
  notify:
    - reload systemd

- name: start and enable rclone services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - gdrive-crypt
    - gdrive-crypt-http
  when:
    - media_rclone_enabled|default(false)|bool == true
