---
- name: install chronyd
  tags: chrony
  become: true
  package:
    name: chrony
    state: present
  register: chrony_install

- name: copy the chrony.conf and chrony.sysconfig template file
  tags: chrony
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: chrony
    mode: "{{ item.mode }}"
  when: chrony_install is success
  with_items:
  - { src: chrony_conf.j2, dest: /etc/chrony.conf, mode: '0644' }
  - { src: chrony_sysconfig.j2, dest: /etc/sysconfig/chronyd, mode: '0644' }
  notify: 
  - restart chrony

- name: start and enable chronyd service
  tags: chronyd
  become: true
  service:
    name: chronyd
    state: started
    enabled: yes
  when: chrony_install is success

- name: configure firewalld for ntp/chrony
  firewalld:
    service: ntp
    permanent: yes
    state: enabled
