---
- name: disable ubuntu motd news
  replace:
    path: /etc/default/motd-news
    regexp: '^ENABLED=1'
    replace: 'ENABLED=0'
  when: managed_motd.enabled|default(false)|bool == true

- name: remove /etc/update-motd.d/10-help-text
  file:
    path: /etc/update-motd.d/10-help-text
    state: absent
  when: managed_motd.enabled|default(false)|bool == true

- name: remove /etc/update-motd.d/motd-news/80-esm
  file:
    path: /etc/update-motd.d/motd-news/80-esm
    state: absent
  when: managed_motd.enabled|default(false)|bool == true

- name: remove /etc/update-motd.d/motd-news/80-livepatch
  file:
    path: /etc/update-motd.d/motd-news/80-livepatch
    state: absent
  when: managed_motd.enabled|default(false)|bool == true

- name: install motd landscape and update-notifier
  package:
    name: ['landscape-common', 'update-notifier-common']
    state: present
  when: managed_motd.enabled|default(false)|bool == true
