---
- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ managed_packages_install }}"
  when:
    - managed_packages_enabled|default(false)|bool == true

- name: remove packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ managed_packages_remove }}"
  when:
    - managed_packages_enabled|default(false)|bool == true
