---
- name: install ssmtp
  tags: ssmtp
  become: true
  package:
    name: ssmtp
    state: present
  register: ssmtp_install
  when: managed_ssmtp.enabled|default(false)|bool == true

- name: configure /etc/ssmtp/ssmtp.conf
  tags: ssmtp
  become: true
  template:
    src: ssmtp_conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644
  when: ssmtp_install is success and managed_ssmtp.enabled|default(false)|bool == true

- name: configure /etc/ssmtp/revaliases
  tags: ssmtp
  become: true
  template:
    src: revaliases.j2
    dest: /etc/ssmtp/revaliases
    owner: root
    group: root
    mode: 0644
  when: ssmtp_install is success and managed_ssmtp.enabled|default(false)|bool == true
