---
- name: install nplan
  package:
    name: ['nplan', 'netplan.io']
    state: present
  register: netplan_install
  when: managed_nplan.enabled|default(false)|bool == true

- name: "configure /etc/netplan/{{ managed_nplan.config.file }}"
  template:
    src: netplan_conf.j2
    dest: "/etc/netplan/{{ managed_nplan.config.file }}"
    owner: root
    group: root
    mode: 0640
  when: netplan_install is success and managed_nplan.enabled|default(false)|bool == true
  notify: reload netplan

- name: find existing configurations
  find:
    paths: /etc/netplan
    patterns: "*.yml,*.yaml"
  register: _netplan_configs

- debug: var=_netplan_configs
  when: debug is defined and ( debug | bool )

- name: remove existing configurations
  file:
    path: "{{ item['path'] }}"
    state: absent
  become: true
  with_items: "{{ _netplan_configs['files'] }}"
  when:
  - item['path'] != "/etc/netplan/{{ managed_nplan.config.file }}"
  - managed_nplan.network != []
  - managed_nplan.enabled|default(false)|bool == true
