---
- name: install packages
  package:
    name: ['fuse', 'gettext', 'mediainfo', 'libmediainfo', 'sqlite', 'libzen', 'HandBrake', 'java', 'libdrm', 'ffmpeg', 'https://downloads.rclone.org/rclone-current-linux-amd64.rpm']
    state: present
  register: fuse_install
  when: app_mediamgmt.enabled|default(false)|bool == true

- name: create folders
  file:
    path: "{{ item.folder }}"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
  - folder: "/home/{{ app_mediamgmt.user }}/.config"
    user: "{{ app_mediamgmt.user }}"
    group: "{{ app_mediamgmt.group }}"
    mode: "0750"
  - folder: "/home/{{ app_mediamgmt.user }}/.config/rclone"
    user: "{{ app_mediamgmt.user }}"
    group: "{{ app_mediamgmt.group }}"
    mode: "0750"
  - folder: "/mnt/{{ app_mediamgmt.config.mountfolder }}"
    user: "{{ app_mediamgmt.user }}"
    group: "{{ app_mediamgmt.group }}"
    mode: "0755"
  - folder: "/mnt/{{ app_mediamgmt.config.mountfolder }}/{{ app_mediamgmt.config.rclone_cryptfolder }}"
    user: "{{ app_mediamgmt.user }}"
    group: "{{ app_mediamgmt.group }}"
    mode: "0755"
  when:
  - app_mediamgmt.enabled|default(false)|bool == true

- name: change ownership of /opt/NzbDrone
  command: "chown -R {{ app_mediamgmt.user }} "
  when: app_mediamgmt.enabled|default(false)|bool == true

- name: configure /etc/fuse.conf
  replace:
    path: /etc/fuse.conf
    regexp: '{{ item.key }}'
    replace: '{{ item.value }}'
  with_items:
  - key: '# mount_max = 1000'
    value: 'mount_max = 1000'
  - key: '# user_allow_other'
    value: 'user_allow_other'
  when:
  - fuse_install is success
  - app_mediamgmt.enabled|default(false)|bool == true

- name: copy configs and systemd units
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    force: "{{ item.force }}"
  with_items:
  - src: conf_rclone.j2
    dest: "/home/{{ app_mediamgmt.user }}/.config/rclone/rclone.conf"
    owner: "{{ app_mediamgmt.user }}"
    group: "{{ app_mediamgmt.group }}"
    mode: "0640"
    force: no
  - src: conf_plex.j2
    dest: "/home/{{ app_mediamgmt.user }}/.config/plex/Plex\ Media\ Server/Preferences.xml"
    owner: "{{ app_mediamgmt.user }}"
    group: "{{ app_mediamgmt.group }}"
    mode: "0640"
    force: no
  - src: conf_sonarr.j2
    dest: "/home/{{ app_mediamgmt.user }}/.config/NzbDrone/config.xml"
    owner: "{{ app_mediamgmt.user }}"
    group: "{{ app_mediamgmt.group }}"
    mode: "0640"
    force: yes
  - src: conf_caddy.j2
    dest: "/etc/caddy/caddy.conf"
    owner: root
    group: root
    mode: "0644"
    force: yes
  - src: service_plexcrypt.j2
    dest: "/etc/systemd/system/plexcrypt.service"
    owner: root
    group: root
    mode: "0644"
    force: yes
  - src: service_plexcrypthttp.j2
    dest: "/etc/systemd/system/plexcrypthttp.service"
    owner: root
    group: root
    mode: "0644"
    force: yes
  - src: service_tautulli.j2
    dest: "/etc/systemd/system/tautulli.service"
    owner: root
    group: root
    mode: "0644"
    force: yes
  - src: service_plex_override.j2
    dest: "/etc/systemd/system/plexmediaserver.service.d/override.conf"
    owner: root
    group: root
    mode: "0644"
    force: yes
  - src: service_sonarr.j2
    dest: "/etc/systemd/system/sonarr.service"
    owner: root
    group: root
    mode: "0644"
    force: yes
  when:
  - app_mediamgmt.enabled|default(false)|bool == true
  notify:
  - reload systemd

- name: configure system settings, file descriptors and number of threads
  pam_limits:
    domain: caddy
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
  - { limit_type: '-', limit_item: 'nofile', value: 8192 }
  - { limit_type: '-', limit_item: 'nproc', value: 8192 }
  - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
  - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

- name: reload settings from all system configuration files
  shell: sysctl --system

- name: copy plexmediaserver ufw rule
  copy:
    src: "{{ role_path }}/files/plexmediaserver.ufw"
    dest: /etc/ufw/applications.d/plexmediaserver
    owner: root
    group: root
    mode: 0644
  when:
  - app_mediamgmt.enabled|default(false)|bool == true

- name: copy local file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0774
  with_items:
  - src: "{{ role_path }}/files/mediabackup.sh"
    dest: "/usr/local/bin/mediabackup.sh"
    owner: "{{ app_mediamgmt.user }}"
    group: "{{ app_mediamgmt.group }}"
  - src: "{{ role_path }}/files/2mp4"
    dest: "/usr/local/bin/2mp4"
    owner: "{{ app_mediamgmt.user }}"
    group: root
  when:
  - app_mediamgmt.enabled|default(false)|bool == true

- name: add crontab entry
  cron:
    name: "backup mediaserver configs and databases"
    minute: "30"
    hour: "05"
    weekday: "*"
    job: "/bin/bash /usr/local/bin/mediabackup.sh"
    #user: "admin"
    disabled: "no"
  become_user: "{{ app_mediamgmt.user }}"

- name: allow plexmediaserver on ufw
  ufw:
    rule: allow
    name: plexmediaserver
  with_items:
  - plexmediaserver
  - "WWW Full"
  when:
  - app_mediamgmt.enabled|default(false)|bool == true
  notify: restart ufw

- name: start and enable mediaserver services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
  - plexcrypt
  - plexcrypthttp
  - plexmediaserver
  - tautulli
  - sonarr
  - caddy
  when:
  - app_mediamgmt.enabled|default(false)|bool == true
