---
- name: create vgs
  tags: vgs
  become: true
  lvg:
    vg: "{{ item.vg }}"
    pvs: "{{ item..pvs | join(',') }}"
    state: present
  with_items:
    - "{{ managed_lvm.vgs }}"
  loop_control:
    label: "{{ item.vg }}"
  when: managed_lvm.enabled|default(false)|bool == true

- name: create lvg
  tags: lvg
  become: true
  lvol:
    vg: "{{ item.vg }}"
    lv: "{{ item.lv }}"
    size: "{{ item.size }}"
    state: "present"
  with_items: "{{ managed_lvm.lvs }}"
  loop_control:
    label: "{{ item.lv }}"
  when: managed_lvm.enabled|default(false)|bool == true

- name: create fs
  tags: create_fs
  become: true
  filesystem:
    fstype: "{{ item.fstype }}"
    dev: "/dev/{{ item.vg }}/{{ item.lv }}"
  with_items: "{{ managed_lvm.lvs }}"
  loop_control:
    label: "{{ item.lv }}"
  when: managed_lvm.enabled|default(false)|bool == true

- name: mount lv
  tags: mount_lv
  become: true
  mount:
    src: "/dev/{{ item.vg }}/{{ item.lv }}"
    path: "{{ item.mount }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.mount_opts }}"
    dump: "{{ item.mount_dump }}"
    passno: "{{ item.mount_passno }}"
    state: "mounted"
  with_items: "{{ managed_lvm.lvs }}"
  loop_control:
    label: "{{ item.lv }}"
  when: managed_lvm.enabled|default(false)|bool == true

- name: set mount permissions
  tags: set_mount_permissions
  become: true
  file:
    path: "{{ item.mount }}"
    owner: "{{ item.mount_owner }}"
    group: "{{ item.mount_group }}"
    mode: "{{ item.mount_mode }}"
  with_items: "{{ managed_lvm.lvs }}"
  loop_control:
    label: "{{ item.mount }}"
  when: managed_lvm.enabled|default(false)|bool == true
