- name: install packages
  package:
    name: ['java-1.8.0-openjdk', 'mediainfo', 'libmediainfo', 'libzen']
    state: present
  register: fuse_install
  when: app_filebot.enabled|default(false)|bool == true

- name: "check for installation"
  stat:
    path: "{{ app_filebot.filebot_bin }}"
  register: filebot_bin
  when: app_filebot.enabled|default(false)|bool == true

#- name: "download installer"
#  get_url:
#    url: "{{ app_filebot.filebot_url }}"
#    dest: "{{ app_filebot.filebot_tmp }}"
#  when: app_filebot.enabled|default(false)|bool == true and not filebot_bin.stat.exists

- name: copy FileBot_4.7.9-portable.tar.xz
  copy:
    src: "{{ role_path }}/files/FileBot_4.7.9-portable.tar.xz"
    dest: "{{ app_filebot.filebot_tmp }}"
    owner: root
    group: root
  when: app_filebot.enabled|default(false)|bool == true and not filebot_bin.stat.exists

- name: "ensure install directory exists"
  file:
    path: "{{ app_filebot.filebot_install }}"
    state: directory
  when: app_filebot.enabled|default(false)|bool == true

- name: "ensure the binaries extracted"
  unarchive:
    copy: "no"
    src: "{{ app_filebot.filebot_tmp }}"
    dest: "{{ app_filebot.filebot_install }}/"
  when: app_filebot.enabled|default(false)|bool == true and not filebot_bin.stat.exists

- name: "ensure link on path to filebot bin"
  file:
    src: "{{ app_filebot.filebot_install }}/filebot.sh"
    dest: "{{ app_filebot.filebot_bin }}"
    state: link
  when: app_filebot.enabled|default(false)|bool == true

- name: "remove installer from tmp"
  file:
    path: "{{ app_filebot.filebot_tmp }}"
    state: absent
  when: app_filebot.enabled|default(false)|bool == true

- name: change ownership of /usr/local/lib/filebot
  command: "chown -R {{ app_filebot.user }} {{ app_filebot.filebot_install }}"
  when: app_filebot.enabled|default(false)|bool == true

- name: copy config for opensubtitles
  template:
    src: prefs.properties.j2
    dest: "{{ app_filebot.filebot_install }}/data/prefs.properties"
    owner: "{{ app_filebot.user }}"
    group: root
    mode: 0644

- name: set symlinks for libs
  file:
    src: "{{ item.src }}"
    dest: "{{ app_filebot.filebot_install }}/{{ item.dest }}"
    state: link
  with_items:
  - src: /usr/lib64/libmediainfo.so.0
    dest: libmediainfo.so
  - src: /usr/lib64/libzen.so.0
    dest: libzen.so
  when: app_filebot.enabled|default(false)|bool == true
