---
- name: install chronyd
  tags: chrony
  become: true
  package:
    name: chrony
    state: present
  register: chrony_install
  when: managed_chrony.enabled|default(false)|bool == true

- name: configure /etc/chrony.conf & /etc/sysconfig/chronyd
  tags: chrony
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: chrony
    mode: "{{ item.mode }}"
  when:
  - chrony_install is success
  - managed_chrony.enabled|default(false)|bool == true
  with_items:
  - { src: chrony_conf.j2, dest: /etc/chrony.conf, mode: '0644' }
  - { src: chrony_sysconfig.j2, dest: /etc/sysconfig/chronyd, mode: '0644' }
  notify: 
  - restart chronyd

- name: start and enable chronyd service
  tags: chronyd
  become: true
  service:
    name: chronyd
    state: started
    enabled: yes
  when:
  - chrony_install is success
  - managed_chrony.enabled|default(false)|bool == true
