---
- name: configure /etc/sudoers for passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  when: managed_ansibleuser.enabled|default(false)|bool == true

- name: create ansible user
  user:
    name: "{{ managed_ansibleuser.name }}"
    groups: sudo
    password: "{{ managed_ansibleuser.pass }}"
    shell: /bin/bash
    comment: "{{ managed_ansibleuser.comment }}"
    update_password: always
    state: present
  when: managed_ansibleuser.enabled|default(false)|bool == true

- name: add authorized key for ansible user
  authorized_key:
    exclusive: true
    state: present
    user: "{{ managed_ansibleuser.name }}"
    key: "{{ managed_ansibleuser.key }}"
  when: managed_ansibleuser.enabled|default(false)|bool == true
