---
- name: install powerline & fonts-powerline
  package:
    name: ['powerline', 'fonts-powerline']
    state: present
  register: powerline_install
  when: managed_prompt.enabled|default(false)|bool == true

- name: configure /etc/bash.bashrc
  blockinfile:
    path: /etc/bash.bashrc
    insertafter: EOF
    state: present
    content: |
      if [ -f ` which powerline-daemon` ]; then
        powerline-daemon -q
        POWERLINE_BASH_CONTINUATION=1
        POWERLINE_BASH_SELECT=1
        . /usr/share/powerline/bindings/bash/powerline.sh
      fi
  when: powerline_install is success and managed_prompt.enabled|default(false)|bool == true
